spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGODB_URI}

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
  auth:
    token: ${TWILIO_AUTH_TOKEN}
  api:
    key: ${TWILIO_API_KEY}
    secret: ${TWILIO_API_SECRET}
  twiml:
    app:
      sid: ${TWILIO_TWIML_APP_SID}

openai:
  model: gpt-4o
  secret-key: ${OPENAI_API_KEY}

gcp:
  project:
    id: ${GCP_PROJECT_ID}
  location:
    id: ${GCP_LOCATION_ID}

elasticsearch:
  host: elasticsearch
  port: 9200
  enabled: true

fastapi:
  url: http://abusefilter:8080/api/abuse/filter

chatbot:
  url: http://chatbot:8000

solapi:
  api-key: ${SOLAPI_API_KEY}
  api-secret: ${SOLAPI_API_SECRET}
  sender: ${SOLAPI_SENDER}